export const Constants = {
    ADD_TODO:'ADD:TODO',
    CHANGE_STATUS: 'CHANGE:TODO_STATUS',
    CHANGE_IS_PIN: 'CHANGE:TODO_PIN',
    DELETE_TODO:'DELETE:TODO',
    AUTH_INITIALIZE: 'INITIALIZE:AUTH',
    AUTH_FACEBOOK:'LOGIN:FACEBOOK',
    AUTH_GOOGLE:'LOGIN:GOOGLE',
    AUTH_GITHUB:'LOGIN:GITHUB',
    AUTH_SUCCESS:'FACEBOOK:SUCCESS',
    AUTH_ERROR:'FACEBOOK:ERROR',
    LOGOUT:'LOGOUT',
    DATABASE: 'todos',
    GET_TODO_SUCCESS: 'GET:TODOS',
    GET_TODO_ERROR: 'ERROR:TODOS',
    IS_FETCH: 'FETCH:REQUEST'

}